expensetracker/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('registration/', views.RegistrationUserView.as_view(), name='registration'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('delete/', views.DeleteUserView.as_view(), name='delete')
]

expensetracker/expenses/urls.py
from django.urls import path

from . import views

app_name = 'expenses'

urlpatterns = [
    path('transactions/', views.TransactionListView.as_view(), name = 'transactions'),
    path('create/', views.CreateTransactionView.as_view(), name='create'),
    path('<int:transaction_pk>/delete/', views.DeleteTransactionView.as_view(), name='delete'),
    path('<int:transaction_pk>/update/', views.UpdateTransactionView.as_view(), name='update'),
    path('categories/',views.CategoriesListView.as_view()  ,name='categories'),
    path('statistics/',views.StatisticsView.as_view() ,name='statics')
]

expensetracker/expensetracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('expenses/', include('expenses.urls')),

]

expensetracker/expenses/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User

class Currency(models.Model):
    shortcut = models.CharField(max_length=5, unique=True)
    country = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return f'{self.country} - {self.shortcut}'

    class Meta:
        verbose_name = 'Currency'
        verbose_name_plural = 'Currencies'
        ordering = ('country',)



class Category(models.Model):
   
    name = models.CharField(max_length=25, unique=True)
    
    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('name',)


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    title = models.CharField(max_length=30, blank=True)
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    transaction_types=(
        ('E','Expence'),
        ('I','Income')
    )
    type = models.CharField(max_length=1, choices=transaction_types, default='E')
    description = models.CharField(max_length=255, blank=True)
    date = models.DateTimeField(blank=True)
    update_date = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = timezone.now()
        return super(Transaction, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.user.username}, {self.category.name}, {self.currency.shortcut}, {self.amount}'

    class Meta:
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'


class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.amount}'    

    class Meta:
        verbose_name = 'Budget'
        verbose_name_plural = 'Budgets'

expensetracker/expenses/forms.py
import datetime

from django import forms

from .models import Transaction
from .services import convert_str_to_datetime, get_time_now


class TransactionCreateForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(), required=False)
    date = forms.DateTimeField(required=False, initial=datetime.datetime.now().date, widget=forms.TextInput(
        attrs={'type': 'date'}
    ))
    time = forms.TimeField(required=False, initial=get_time_now(),  widget=forms.TextInput(
        attrs={'type': 'time'}
    ))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        self.user = self.request.user
        if 'data' in kwargs:
            self.date = kwargs['data']['date']
            self.time = kwargs['data']['time']
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        transaction = super().save(commit=False)
        transaction.user = self.user

        if self.data and self.time:
            transaction.date = convert_str_to_datetime(self.date, self.time)
        if commit:
            transaction.save()
        return transaction

    class Meta:
        model = Transaction
        fields = ('type', 'category', 'amount', 'currency',
                  'title', 'description', 'date', 'time')


class UpdateTransactionForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Transaction
        fields = ('type', 'category', 'amount', 'currency',
                  'title', 'description')

expensetracker/expenses/views.py
from datetime import datetime

from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Budget, Category, Transaction
from .forms import TransactionCreateForm, UpdateTransactionForm
from accounts.models import User
from .services import get_user_trans_data, statistics_img


class TransactionListView(ListView):
    template_name = 'expenses/transactions.html'
    context_object_name = 'transaction_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_amount'] = self.total_amount
        # if self.budget:
        #     context['budget'] = self.budget
        return context

    def get_queryset(self):
        self.user = get_object_or_404(User, pk=self.request.user.pk)
        queryset = Transaction.objects.filter(user=self.user).order_by('-date')
        self.total_amount = get_user_trans_data(self.user, total_amount=True)
        self.budget = Budget.objects.filter(
            user=self.user).order_by('-date').first()
        return queryset


class CreateTransactionView(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = 'expenses/transaction_create.html'
    form_class = TransactionCreateForm
    success_url = reverse_lazy('expenses:transactions')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class UpdateTransactionView(LoginRequiredMixin, UpdateView):
    model = Transaction
    template_name = 'expenses/transaction_update.html'
    form_class = UpdateTransactionForm
    success_url = reverse_lazy('expenses:transactions')

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(Transaction, pk=self.kwargs['transaction_pk'])


class DeleteTransactionView(LoginRequiredMixin, DeleteView):
    model = Transaction
    success_url = reverse_lazy('expenses:transactions')

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(Transaction, pk=self.kwargs['transaction_pk'])

    # No confirmation template
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CategoriesListView(ListView):
    template_name = 'expenses/categories.html'
    context_object_name = 'category_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['by_category'] = self.by_category

        return context

    def get_queryset(self):
        self.user = get_object_or_404(User, pk=self.request.user.pk)
        queryset = Category.objects.all()
        self.by_category = get_user_trans_data(
            self.user, categories_amount=True)

        return queryset


class StatisticsView(TemplateView):
    template_name = 'expenses/statistics.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, pk=self.request.user.pk)
        context['graphic_1'] = statistics_img(user, months_amount=True)
        context['graphic_2'] = statistics_img(user, categories_amount=True)
        context['graphic_3'] = statistics_img(user, total_income=True)
        return context

expensetracker/expenses/templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Expence Tracker{% endblock title %}</title>
    {% bootstrap_css %}
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/> {% endcomment %}
    {% bootstrap_javascript %}
</head>

<body>
    <div class="d-flex">
        <div class="border-end bg-white position-fixed" style="min-height: 100vh; min-width: 40vh;">
            <div class="list-group list-group-flush">
                {% if request.user.is_authenticated %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'expenses:transactions' %}">Transactions</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'expenses:statics' %}">Statistics</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'expenses:categories' %}">Categories</a>
                    <div class="d-flex justify-content-end">
                        <div class="dropdown">
                            <button class="list-group-item dropdown-toggle" type="button" data-bs-toggle="dropdown" >
                                Profile
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'accounts:logout' %}">Logout</a></li>
                                <li><a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'accounts:delete' %}">Delete</a></li>
                            </ul>
                        </div>
                    </div>
                {% else %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'accounts:login' %}">Sign In</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'accounts:registration' %}">Sign Up</a>
                {% endif %}
            </div>
        </div>
        <div class="d-flex justify-content-center w-100">
            {% block content %}{% endblock content %}
        </div>
    </div>


</body>

</html>