expensetracker/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('registration/', views.RegistrationUserView.as_view(), name='registration'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('delete/', views.DeleteUserView.as_view(), name='delete')
]

expensetracker/expenses/urls.py
from django.urls import path

from . import views

app_name = 'expenses'

urlpatterns = [
    path('transactions/', views.TransactionListView.as_view(), name = 'transactions'),
    path('create/', views.CreateTransactionView.as_view(), name='create'),
    path('<int:transaction_pk>/delete/', views.DeleteTransactionView.as_view(), name='delete'),
    path('<int:transaction_pk>/update/', views.UpdateTransactionView.as_view(), name='update'),
    path('categories/',views.CategoriesListView.as_view()  ,name='categories'),
    path('statistics/',views.StatisticsView.as_view() ,name='statics')
]

expensetracker/expensetracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('expenses/', include('expenses.urls')),

]

expensetracker/expenses/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User

class Currency(models.Model):
    shortcut = models.CharField(max_length=5, unique=True)
    country = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return f'{self.country} - {self.shortcut}'

    class Meta:
        verbose_name = 'Currency'
        verbose_name_plural = 'Currencies'
        ordering = ('country',)



class Category(models.Model):
   
    name = models.CharField(max_length=25, unique=True)
    
    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('name',)


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    title = models.CharField(max_length=30, blank=True)
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    transaction_types=(
        ('E','Expence'),
        ('I','Income')
    )
    type = models.CharField(max_length=1, choices=transaction_types, default='E')
    description = models.CharField(max_length=255, blank=True)
    date = models.DateTimeField(blank=True)
    update_date = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = timezone.now()
        return super(Transaction, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.user.username}, {self.category.name}, {self.currency.shortcut}, {self.amount}'

    class Meta:
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'


class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.amount}'    

    class Meta:
        verbose_name = 'Budget'
        verbose_name_plural = 'Budgets'

expensetracker/expenses/forms.py
import datetime

from django import forms

from .models import Transaction
from .services import convert_str_to_datetime, get_time_now


class TransactionCreateForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(), required=False)
    date = forms.DateTimeField(required=False, initial=datetime.datetime.now().date, widget=forms.TextInput(
        attrs={'type': 'date'}
    ))
    time = forms.TimeField(required=False, initial=get_time_now(),  widget=forms.TextInput(
        attrs={'type': 'time'}
    ))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        self.user = self.request.user
        if 'data' in kwargs:
            self.date = kwargs['data']['date']
            self.time = kwargs['data']['time']
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        transaction = super().save(commit=False)
        transaction.user = self.user

        if self.data and self.time:
            transaction.date = convert_str_to_datetime(self.date, self.time)
        if commit:
            transaction.save()
        return transaction

    class Meta:
        model = Transaction
        fields = ('type', 'category', 'amount', 'currency',
                  'title', 'description', 'date', 'time')


class UpdateTransactionForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Transaction
        fields = ('type', 'category', 'amount', 'currency',
                  'title', 'description')

expensetracker/expenses/views.py
from datetime import datetime

from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Budget, Category, Transaction
from .forms import TransactionCreateForm, UpdateTransactionForm
from accounts.models import User
from .services import get_user_trans_data, statistics_img


class TransactionListView(ListView):
    template_name = 'expenses/transactions.html'
    context_object_name = 'transaction_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_amount'] = self.total_amount
        # if self.budget:
        #     context['budget'] = self.budget
        return context

    def get_queryset(self):
        self.user = get_object_or_404(User, pk=self.request.user.pk)
        queryset = Transaction.objects.filter(user=self.user).order_by('-date')
        self.total_amount = get_user_trans_data(self.user, total_amount=True)
        self.budget = Budget.objects.filter(
            user=self.user).order_by('-date').first()
        return queryset


class CreateTransactionView(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = 'expenses/transaction_create.html'
    form_class = TransactionCreateForm
    success_url = reverse_lazy('expenses:transactions')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class UpdateTransactionView(LoginRequiredMixin, UpdateView):
    model = Transaction
    template_name = 'expenses/transaction_update.html'
    form_class = UpdateTransactionForm
    success_url = reverse_lazy('expenses:transactions')

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(Transaction, pk=self.kwargs['transaction_pk'])


class DeleteTransactionView(LoginRequiredMixin, DeleteView):
    model = Transaction
    success_url = reverse_lazy('expenses:transactions')

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(Transaction, pk=self.kwargs['transaction_pk'])

    # No confirmation template
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CategoriesListView(ListView):
    template_name = 'expenses/categories.html'
    context_object_name = 'category_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['by_category'] = self.by_category

        return context

    def get_queryset(self):
        self.user = get_object_or_404(User, pk=self.request.user.pk)
        queryset = Category.objects.all()
        self.by_category = get_user_trans_data(
            self.user, categories_amount=True)

        return queryset


class StatisticsView(TemplateView):
    template_name = 'expenses/statistics.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, pk=self.request.user.pk)
        context['graphic_1'] = statistics_img(user, months_amount=True)
        context['graphic_2'] = statistics_img(user, categories_amount=True)
        context['graphic_3'] = statistics_img(user, total_income=True)
        return context

expensetracker/expenses/templates/expenses/categories.html
{% extends 'base.html' %}

{% block title %}Index{% endblock title %}

{% block content %}
    <ul>
        {% for category in category_list %}
            <div class="card m-3" style="width: 100vh;">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h6 class="card-title">{{ category.name }}</h6>
                        <p class="{% if by_category|get_item:category.name < 0 %} text-danger {% else %} text-success {% endif %}">{{ by_category|get_item:category.name }} $</p>
                    </div>
                    
                </div>
            </div>
        {% endfor %}
    </ul>
{% endblock content %}

expensetracker/expenses/templates/expenses/statistics.html
{% extends 'base.html' %}

{% block title %}Statistic{% endblock title %}

{% block content %}
    <div class="col-sm-3 image-container">
    <img src="data:image/png;base64,{{ graphic_1|safe }}">
    <img src="data:image/png;base64,{{ graphic_2|safe }}">
    <img src="data:image/png;base64,{{ graphic_3|safe }}">
    </div>
{% endblock content %}

expensetracker/expenses/templates/expenses/transaction_create.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load crispy_forms_tags %}

{% block title %}Create transaction{% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% comment %} {{ form|crispy }} {% endcomment %}

        <div class="row">
            <div class="col">
                {{ form.type|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.category|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.amount|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.currency|as_crispy_field }}
            </div>
        </div>
        {{ form.title|as_crispy_field }}
        {{ form.description|as_crispy_field }}
        <div class="row">
            <div class="col">
                {{ form.date|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.time|as_crispy_field }}
            </div>
        </div>
        {% buttons submit="Create" %}{% endbuttons %}
    </form>
    
{% endblock content %}

expensetracker/expenses/templates/expenses/transaction_update.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load crispy_forms_tags %}

{% block title %}Create transaction{% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                {{ form.type|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.category|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.amount|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.currency|as_crispy_field }}
            </div>
        </div>
        {{ form.title|as_crispy_field }}
        {{ form.description|as_crispy_field }}
        
        {% buttons submit="Update" %}{% endbuttons %}
    </form>
    
{% endblock content %}

expensetracker/expenses/templates/expenses/transactions.html
{% extends 'base.html' %}

{% block title %}Index{% endblock title %}

{% block content %}
    <ul>
        <div class="card m-3" style="width: 100vh;">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h6 class="card-title text-muted">Transactions</h6>
                     <a href="{% url 'expenses:create' %}" class="link-success me-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                    </a>
                </div>
                {% comment %} <p class="card-subtitle mt-2 mb-3">Budget - {{ budget }} $</p> {% endcomment %}
                <p class="fw-bold card-text{% if total_amount < 0 %} text-danger {% else %} text-success {% endif %}text-center">{{ total_amount }} $</p>
            </div>
        </div>
        {% for transaction in transaction_list %}
            <div class="card m-3" style="width: 100vh;">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h6 class="card-title">{{ transaction.title }}</h6>
                        <p class="card-subtitle {% if transaction.type == 'E' %} text-danger {% else %} text-success {% endif %} mb-3">{{ transaction.amount }} {{ transaction.currency.shortcut }}</p>
                    </div>
                    <div class="d-flex justify-content-between">
                        <span class="border border-secondary rounded-pill">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tags m-1" viewBox="0 0 16 16">
                                <path d="M3 2v4.586l7 7L14.586 9l-7-7H3zM2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2z"/>
                                <path d="M5.5 5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm0 1a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zM1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z"/>
                            </svg>
                            <small class="card-text text-muted text-center me-2">{{ transaction.category }}</small>
                        </span>
                        <span class="border border-secondary rounded-pill">
                            <small class="card-text text-muted text-center m-1 ms-2 me-2">{{ transaction.date|date:"H:i Y-m-d" }}</small>
                        </span>
                    </div>
                    <div class="d-flex justify-content-center mt-2">
                        <a type="button" class="link-secondary me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-eyeglasses" viewBox="0 0 16 16">
                                <path d="M4 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm2.625.547a3 3 0 0 0-5.584.953H.5a.5.5 0 0 0 0 1h.541A3 3 0 0 0 7 8a1 1 0 0 1 2 0 3 3 0 0 0 5.959.5h.541a.5.5 0 0 0 0-1h-.541a3 3 0 0 0-5.584-.953A1.993 1.993 0 0 0 8 6c-.532 0-1.016.208-1.375.547zM14 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
                            </svg>
                        </a>

                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Description</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                {{ transaction.description }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                            </div>
                        </div>
                        </div>
                        <a href="{% url 'expenses:update' transaction_pk=transaction.id %}" class="link-warning me-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg>
                        </a>
                        <a href="{% url 'expenses:delete' transaction_pk=transaction.id %}" class="link-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        </a>
                        
                    </div>
                </div>
            </div>
        {% endfor %}
    </ul>
{% endblock content %}